id: P09F660F4
initial_creation_type: input
source_metadata:
  Title: Āryaprajñāpāramitāvajracchedikāṭīkā
  Editor: Pema Tendzin
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1994'
  Āryaprajñāpāramitāvajracchedikāṭīkā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:46:11.203581'
last_modified_at: '2022-03-08T16:46:11.203592'
